blank_issues_enabled: true
contact_links:
  - name: Pytanie / dyskusja
    url: https://github.com/kkrysztofczyk/kkr-query2xlsx/discussions
    about: Jeśli to pytanie “jak użyć”, wrzuć je w Discussions.
