blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/kkrysztofczyk/kkr-query2xlsx/discussions
    about: If this is a "how do I use it?" question, please use Discussions.
